#ifndef CPPGLOB_IGLOB_HPP
#define CPPGLOB_IGLOB_HPP

#include <cstddef>
#include <iterator>
#include <vector>
#include <filesystem>
#include "config.hpp"
#include "glob_iterator.hpp"

namespace cppglob {
  /**
   * @brief Return an iterator which yields the paths matching a pathname
   * pattern.
   * @param pathname pattern string
   * @param recursive allow recursive pattern string
   *
   * The pattern may contain simple shell-style wildcards a la
   * fnmatch. However, unlike fnmatch, filenames starting with a
   * dot are special cases that are not matched by '*' and '?'
   * patterns.
   *
   * If recursive is true, the pattern '**' will match any files and
   * zero or more directories and subdirectories.
   */
  CPPGLOB_EXPORT glob_iterator iglob(const fs::path& pathname,
                                     bool recursive = false);

  /**
   * @brief Return the end of glob_iterator generated by
   * iglob(pathname, recursive) function.
   */
  CPPGLOB_EXPORT glob_iterator iglob();
}  // namespace cppglob

#endif
